### ISSUE TITLE
Failed to load dynamic library 'libc.so.6': dlopen failed: library "libc.so.6" not found

### ISSUE THREAD

**Issue by ksh-b** [brendan-duncan/archive#361]
Platform: Android 11
archive version: 4.0.1

Steps to reproduce:
Try to use `extractFileToDisk` method for extracting zip file.

This line seems to be causing the issue
[`posix.isPosixSupported`](https://github.com/brendan-duncan/archive/blob/main/lib/src/io/extract_archive_to_disk.dart#L237)

from pubspec.lock:
```
...
  archive:
    dependency: "direct main"
    description:
      name: archive
      sha256: "08064924cbf0ab88280a0c3f60db9dd24fec693927e725ecb176f16c629d1cb8"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.1"
...
  posix:
    dependency: transitive
    description:
      name: posix
      sha256: a0117dc2167805aa9125b82eee515cc891819bac2f538c83646d355b16f58b9a
      url: "https://pub.dev"
    source: hosted
    version: "6.0.1"
```

The method was working fine in archive version 3.6.1
